name: Test

on:
  push:
  pull_request:

jobs:
  test-native:
    name: Report descriptor tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the tests
        run: make -C test_native test
